### ISSUE TITLE
Command history, Command not found - future improvements

### ISSUE THREAD

**Issue by 452** [basilfx/Arduino-CommandLine#1]
possibility to enable and use notification about command not found

``` c
#ifdef COMMAND_NOT_FOUND_MESSAGE
    if (!success) {
       this->serial.println(COMMAND_NOT_FOUND_MESSAGE);
    }
#endif
```

---

useful for command history implementation(like in Linux console):
(for last 5 or 10 commands)

``` c
#define KEYCODE_UP 65
#define KEYCODE_DOWN 66
/**************************/
case KEYCODE_UP:
  if (length > 0) {
    // Move pointer
    length = 0;
    this->serial.write("\33[2K\r");
  }
break;
case KEYCODE_DOWN:
  if (length > 0) {
    // Move pointer
    length = 0;
    this->serial.write("\33[2K\r");
}
break;
```

and this future must have possibility to be enabled like plugin from `#define`

**Comment by basilfx** [comment]
Hi,

Thanks for the feedback. I will look into this when I have the time :-)

Thanks!

**Comment by basilfx** [comment]
It is added in version v2.1.0 that I just pushed.

I have added basic support for history (up/down only, no inline editing or preservation of input) and added generic pre/post callbacks to handle use cases such as 'command not found'.
